version: '2.3'

services:

  nginx:
    container_name: nginx
    restart: always
    build: ./01_nginx
    ports:
      - "80:80"
    depends_on:
      - gradio_frontend

  gradio_frontend:
    container_name: gradio_frontend
    restart: always
    build: ./02_gradio_frontend
    ports:
      - "7000:7000"
    command: python -u wsgi.py

  sd_text2img_app:
    container_name: sd_txt2img_app
    restart: always
    build: ./03_SD_txt2img_app
    runtime: nvidia
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app --timeout 600 --log-level debug
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1

  sd_img2img_app:
    container_name: sd_img2img_app
    restart: always
    build: ./04_SD_img2img_app
    runtime: nvidia
    ports:
      - "9000:9000"
    command: gunicorn -w 1 -b 0.0.0.0:9000 wsgi:app --timeout 600 --log-level debug
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1

  sd_inpainting_app:
      container_name: sd_inpainting_app
      restart: always
      build: ./05_SD_inpainting_app
      runtime: nvidia
      ports:
        - "10000:10000"
      command: gunicorn -w 1 -b 0.0.0.0:10000 wsgi:app --timeout 600 --log-level debug
      deploy:
        resources:
          reservations:
            devices:
              - capabilities:
                - gpu
      shm_size: "8gb"
      ulimits:
        memlock: -1
        stack: 67108864
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:ro
      environment:
        - DISPLAY=$DISPLAY
        - NVIDIA_VISIBLE_DEVICES=all
        - PYTHONUNBUFFERED=1
        - HF_TOKEN=$HF_TOKEN

  clip_interrogator_app:
    container_name: clip_interrogator_app
    restart: always
    build: ./06_clip_interrogator_app
    runtime: nvidia
    ports:
      - "11000:11000"
    command: gunicorn -w 1 -b 0.0.0.0:11000 wsgi:app --timeout 600 --log-level debug
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1

  instruct_pix2pix_app:
      container_name: instruct_pix2pix_app
      restart: always
      build: ./07_instruct_pix2pix_app
      runtime: nvidia
      ports:
        - "12000:12000"
      command: gunicorn -w 1 -b 0.0.0.0:12000 wsgi:app --timeout 600 --log-level debug
      deploy:
        resources:
          reservations:
            devices:
              - capabilities:
                - gpu
      shm_size: "8gb"
      ulimits:
        memlock: -1
        stack: 67108864
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:ro
      environment:
        - DISPLAY=$DISPLAY
        - NVIDIA_VISIBLE_DEVICES=all
        - PYTHONUNBUFFERED=1
        - HF_TOKEN=$HF_TOKEN

  sd_dreambooth_app:
      container_name: sd_dreambooth_app
      restart: always
      build: ./09_SD_dreambooth_app
      runtime: nvidia
      ports:
        - "13000:13000"
      command: gunicorn -w 1 -b 0.0.0.0:13000 wsgi:app --timeout 600 --log-level debug
      deploy:
        resources:
          reservations:
            devices:
              - capabilities:
                - gpu
      shm_size: "8gb"
      ulimits:
        memlock: -1
        stack: 67108864
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:ro
      environment:
        - DISPLAY=$DISPLAY
        - NVIDIA_VISIBLE_DEVICES=all
        - PYTHONUNBUFFERED=1
        - HF_TOKEN=$HF_TOKEN

  # vq_text2img_app:
  #   container_name: vq_txt2img_app
  #   restart: always
  #   build: ./08_vq_txt2img_app
  #   runtime: nvidia
  #   ports:
  #     - "13000:13000"
  #   command: gunicorn -w 1 -b 0.0.0.0:13000 wsgi:app --timeout 600 --log-level debug
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities:
  #             - gpu
  #   shm_size: "8gb"
  #   ulimits:
  #     memlock: -1
  #     stack: 67108864
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:ro
  #   environment:
  #     - DISPLAY=$DISPLAY
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - PYTHONUNBUFFERED=1